# Site settings
title: Felipe Cocco
description: 'Personal Site'
url: 'http://felipecocco.github.io' 
baseurl: '/'
# google_analytics: 'UA-XXXXXX-X'

author:
  name: 'Felipe Cocco'
  email: felipecocco@gmail.com
  twitter_username: felipecocco
  github_username:  felipecocco
  # linkedin_username:  joshgerdes

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: pygments

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']